services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/${ENVIRONMENT}.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/var/www/html
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/basic-auth:/etc/nginx/basic-auth
  
  example-app-1:
    image: sahilng/http-parrot
    platform: ${DOCKER_DEFAULT_PLATFORM}
    expose:
      - "8080"
    environment:
      PORT: 8080
      SAY: Hello, from example app 1!

  example-app-2:
    image: sahilng/http-parrot
    platform: ${DOCKER_DEFAULT_PLATFORM}
    expose:
      - "8080"
    environment:
      PORT: 8080
      SAY: Hello, from example app 2!