services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/${ENVIRONMENT}.conf:/etc/nginx/conf.d/default.conf  # Use as the final config file
      - ./nginx/html:/var/www/html
      - ./nginx/letsencrypt:/etc/letsencrypt  # Mount for SSL certificates
    depends_on:
      - app1
      - app2

  app1:
    build:
      context: ./app1
    container_name: app1
    expose:
      - "5000"
    environment:
      - FLASK_ENV=production

  app2:
    build:
      context: ./app2
    container_name: app2
    expose:
      - "5000"
    environment:
      - FLASK_ENV=production